// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: limk/p2pchat/basic/MessageBasic.proto

package limk.p2pchat.basic;

public final class MessageBasic {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_basic_MessageEntity_descriptor;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_basic_UserEntity_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_basic_MessageEntity_fieldAccessorTable;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_basic_UserEntity_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n%limk/p2pchat/basic/MessageBasic.proto\022" +
                        "\005basic\"\374\002\n\rMessageEntity\022\021\n\tmessageID\030\001 " +
                        "\002(\003\022\014\n\004UUID\030\002 \002(\003\022\023\n\013messageDate\030\003 \002(\t\022\023" +
                        "\n\013messageType\030\004 \002(\005\022\024\n\014messageState\030\005 \002(" +
                        "\005\022\023\n\013messageView\030\006 \002(\005\022\016\n\006isRead\030\007 \002(\010\022\023" +
                        "\n\013messageHead\030\010 \001(\t\022\026\n\016messagePayload\030\t " +
                        "\001(\014\"Y\n\013MessageType\022\007\n\003ACK\020\000\022\t\n\005HELLO\020\001\022\010" +
                        "\n\004WORD\020\002\022\013\n\007PICTURE\020\003\022\t\n\005VOICE\020\004\022\t\n\005VIDE" +
                        "O\020\005\022\t\n\005OTHER\020\006\"$\n\013MessageView\022\010\n\004SEND\020\000\022" +
                        "\013\n\007RECEIVE\020\001\"7\n\014MessageState\022\013\n\007SENDING\020",
                "\000\022\r\n\tSEND_FAIL\020\001\022\013\n\007SEND_OK\020\002\"(\n\nUserEnt" +
                        "ity\022\014\n\004uuid\030\001 \002(\003\022\014\n\004name\030\002 \002(\tB\"\n\022limk." +
                        "p2pchat.basicB\014MessageBasic"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_basic_MessageEntity_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_basic_MessageEntity_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_basic_MessageEntity_descriptor,
                new java.lang.String[]{"MessageID", "UUID", "MessageDate", "MessageType", "MessageState", "MessageView", "IsRead", "MessageHead", "MessagePayload",});
        internal_static_basic_UserEntity_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_basic_UserEntity_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_basic_UserEntity_descriptor,
                new java.lang.String[]{"Uuid", "Name",});
    }

    private MessageBasic() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    public interface MessageEntityOrBuilder extends
            // @@protoc_insertion_point(interface_extends:basic.MessageEntity)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required int64 messageID = 1;</code>
         */
        boolean hasMessageID();

        /**
         * <code>required int64 messageID = 1;</code>
         */
        long getMessageID();

        /**
         * <code>required int64 UUID = 2;</code>
         */
        boolean hasUUID();

        /**
         * <code>required int64 UUID = 2;</code>
         */
        long getUUID();

        /**
         * <code>required string messageDate = 3;</code>
         */
        boolean hasMessageDate();

        /**
         * <code>required string messageDate = 3;</code>
         */
        java.lang.String getMessageDate();

        /**
         * <code>required string messageDate = 3;</code>
         */
        com.google.protobuf.ByteString
        getMessageDateBytes();

        /**
         * <code>required int32 messageType = 4;</code>
         */
        boolean hasMessageType();

        /**
         * <code>required int32 messageType = 4;</code>
         */
        int getMessageType();

        /**
         * <code>required int32 messageState = 5;</code>
         */
        boolean hasMessageState();

        /**
         * <code>required int32 messageState = 5;</code>
         */
        int getMessageState();

        /**
         * <code>required int32 messageView = 6;</code>
         */
        boolean hasMessageView();

        /**
         * <code>required int32 messageView = 6;</code>
         */
        int getMessageView();

        /**
         * <code>required bool isRead = 7;</code>
         */
        boolean hasIsRead();

        /**
         * <code>required bool isRead = 7;</code>
         */
        boolean getIsRead();

        /**
         * <code>optional string messageHead = 8;</code>
         */
        boolean hasMessageHead();

        /**
         * <code>optional string messageHead = 8;</code>
         */
        java.lang.String getMessageHead();

        /**
         * <code>optional string messageHead = 8;</code>
         */
        com.google.protobuf.ByteString
        getMessageHeadBytes();

        /**
         * <code>optional bytes messagePayload = 9;</code>
         */
        boolean hasMessagePayload();

        /**
         * <code>optional bytes messagePayload = 9;</code>
         */
        com.google.protobuf.ByteString getMessagePayload();
    }

    public interface UserEntityOrBuilder extends
            // @@protoc_insertion_point(interface_extends:basic.UserEntity)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required int64 uuid = 1;</code>
         */
        boolean hasUuid();

        /**
         * <code>required int64 uuid = 1;</code>
         */
        long getUuid();

        /**
         * <code>required string name = 2;</code>
         */
        boolean hasName();

        /**
         * <code>required string name = 2;</code>
         */
        java.lang.String getName();

        /**
         * <code>required string name = 2;</code>
         */
        com.google.protobuf.ByteString
        getNameBytes();
    }

    /**
     * Protobuf type {@code basic.MessageEntity}
     */
    public static final class MessageEntity extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:basic.MessageEntity)
            MessageEntityOrBuilder {
        public static final int MESSAGEID_FIELD_NUMBER = 1;
        public static final int UUID_FIELD_NUMBER = 2;
        public static final int MESSAGEDATE_FIELD_NUMBER = 3;
        public static final int MESSAGETYPE_FIELD_NUMBER = 4;
        public static final int MESSAGESTATE_FIELD_NUMBER = 5;
        public static final int MESSAGEVIEW_FIELD_NUMBER = 6;
        public static final int ISREAD_FIELD_NUMBER = 7;
        public static final int MESSAGEHEAD_FIELD_NUMBER = 8;
        public static final int MESSAGEPAYLOAD_FIELD_NUMBER = 9;
        private static final MessageEntity defaultInstance;
        private static final long serialVersionUID = 0L;
        public static com.google.protobuf.Parser<MessageEntity> PARSER =
                new com.google.protobuf.AbstractParser<MessageEntity>() {
                    public MessageEntity parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new MessageEntity(input, extensionRegistry);
                    }
                };

        static {
            defaultInstance = new MessageEntity(true);
            defaultInstance.initFields();
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;
        private int bitField0_;
        private long messageID_;
        private long uUID_;
        private java.lang.Object messageDate_;
        private int messageType_;
        private int messageState_;
        private int messageView_;
        private boolean isRead_;
        private java.lang.Object messageHead_;
        private com.google.protobuf.ByteString messagePayload_;
        private byte memoizedIsInitialized = -1;
        private int memoizedSerializedSize = -1;

        // Use MessageEntity.newBuilder() to construct.
        private MessageEntity(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private MessageEntity(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private MessageEntity(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            messageID_ = input.readInt64();
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            uUID_ = input.readInt64();
                            break;
                        }
                        case 26: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000004;
                            messageDate_ = bs;
                            break;
                        }
                        case 32: {
                            bitField0_ |= 0x00000008;
                            messageType_ = input.readInt32();
                            break;
                        }
                        case 40: {
                            bitField0_ |= 0x00000010;
                            messageState_ = input.readInt32();
                            break;
                        }
                        case 48: {
                            bitField0_ |= 0x00000020;
                            messageView_ = input.readInt32();
                            break;
                        }
                        case 56: {
                            bitField0_ |= 0x00000040;
                            isRead_ = input.readBool();
                            break;
                        }
                        case 66: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000080;
                            messageHead_ = bs;
                            break;
                        }
                        case 74: {
                            bitField0_ |= 0x00000100;
                            messagePayload_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static MessageEntity getDefaultInstance() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return limk.p2pchat.basic.MessageBasic.internal_static_basic_MessageEntity_descriptor;
        }

        public static limk.p2pchat.basic.MessageBasic.MessageEntity parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static limk.p2pchat.basic.MessageBasic.MessageEntity parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static limk.p2pchat.basic.MessageBasic.MessageEntity parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static limk.p2pchat.basic.MessageBasic.MessageEntity parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static limk.p2pchat.basic.MessageBasic.MessageEntity parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static limk.p2pchat.basic.MessageBasic.MessageEntity parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static limk.p2pchat.basic.MessageBasic.MessageEntity parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static limk.p2pchat.basic.MessageBasic.MessageEntity parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static limk.p2pchat.basic.MessageBasic.MessageEntity parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static limk.p2pchat.basic.MessageBasic.MessageEntity parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public static Builder newBuilder(limk.p2pchat.basic.MessageBasic.MessageEntity prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public MessageEntity getDefaultInstanceForType() {
            return defaultInstance;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return limk.p2pchat.basic.MessageBasic.internal_static_basic_MessageEntity_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            limk.p2pchat.basic.MessageBasic.MessageEntity.class, limk.p2pchat.basic.MessageBasic.MessageEntity.Builder.class);
        }

        @java.lang.Override
        public com.google.protobuf.Parser<MessageEntity> getParserForType() {
            return PARSER;
        }

        /**
         * <code>required int64 messageID = 1;</code>
         */
        public boolean hasMessageID() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required int64 messageID = 1;</code>
         */
        public long getMessageID() {
            return messageID_;
        }

        /**
         * <code>required int64 UUID = 2;</code>
         */
        public boolean hasUUID() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>required int64 UUID = 2;</code>
         */
        public long getUUID() {
            return uUID_;
        }

        /**
         * <code>required string messageDate = 3;</code>
         */
        public boolean hasMessageDate() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>required string messageDate = 3;</code>
         */
        public java.lang.String getMessageDate() {
            java.lang.Object ref = messageDate_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    messageDate_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string messageDate = 3;</code>
         */
        public com.google.protobuf.ByteString
        getMessageDateBytes() {
            java.lang.Object ref = messageDate_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                messageDate_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>required int32 messageType = 4;</code>
         */
        public boolean hasMessageType() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }

        /**
         * <code>required int32 messageType = 4;</code>
         */
        public int getMessageType() {
            return messageType_;
        }

        /**
         * <code>required int32 messageState = 5;</code>
         */
        public boolean hasMessageState() {
            return ((bitField0_ & 0x00000010) == 0x00000010);
        }

        /**
         * <code>required int32 messageState = 5;</code>
         */
        public int getMessageState() {
            return messageState_;
        }

        /**
         * <code>required int32 messageView = 6;</code>
         */
        public boolean hasMessageView() {
            return ((bitField0_ & 0x00000020) == 0x00000020);
        }

        /**
         * <code>required int32 messageView = 6;</code>
         */
        public int getMessageView() {
            return messageView_;
        }

        /**
         * <code>required bool isRead = 7;</code>
         */
        public boolean hasIsRead() {
            return ((bitField0_ & 0x00000040) == 0x00000040);
        }

        /**
         * <code>required bool isRead = 7;</code>
         */
        public boolean getIsRead() {
            return isRead_;
        }

        /**
         * <code>optional string messageHead = 8;</code>
         */
        public boolean hasMessageHead() {
            return ((bitField0_ & 0x00000080) == 0x00000080);
        }

        /**
         * <code>optional string messageHead = 8;</code>
         */
        public java.lang.String getMessageHead() {
            java.lang.Object ref = messageHead_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    messageHead_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string messageHead = 8;</code>
         */
        public com.google.protobuf.ByteString
        getMessageHeadBytes() {
            java.lang.Object ref = messageHead_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                messageHead_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>optional bytes messagePayload = 9;</code>
         */
        public boolean hasMessagePayload() {
            return ((bitField0_ & 0x00000100) == 0x00000100);
        }

        /**
         * <code>optional bytes messagePayload = 9;</code>
         */
        public com.google.protobuf.ByteString getMessagePayload() {
            return messagePayload_;
        }

        private void initFields() {
            messageID_ = 0L;
            uUID_ = 0L;
            messageDate_ = "";
            messageType_ = 0;
            messageState_ = 0;
            messageView_ = 0;
            isRead_ = false;
            messageHead_ = "";
            messagePayload_ = com.google.protobuf.ByteString.EMPTY;
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasMessageID()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasUUID()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasMessageDate()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasMessageType()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasMessageState()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasMessageView()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasIsRead()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt64(1, messageID_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeInt64(2, uUID_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeBytes(3, getMessageDateBytes());
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeInt32(4, messageType_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                output.writeInt32(5, messageState_);
            }
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
                output.writeInt32(6, messageView_);
            }
            if (((bitField0_ & 0x00000040) == 0x00000040)) {
                output.writeBool(7, isRead_);
            }
            if (((bitField0_ & 0x00000080) == 0x00000080)) {
                output.writeBytes(8, getMessageHeadBytes());
            }
            if (((bitField0_ & 0x00000100) == 0x00000100)) {
                output.writeBytes(9, messagePayload_);
            }
            getUnknownFields().writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(1, messageID_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(2, uUID_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(3, getMessageDateBytes());
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(4, messageType_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(5, messageState_);
            }
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(6, messageView_);
            }
            if (((bitField0_ & 0x00000040) == 0x00000040)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(7, isRead_);
            }
            if (((bitField0_ & 0x00000080) == 0x00000080)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(8, getMessageHeadBytes());
            }
            if (((bitField0_ & 0x00000100) == 0x00000100)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(9, messagePayload_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf enum {@code basic.MessageEntity.MessageType}
         */
        public enum MessageType
                implements com.google.protobuf.ProtocolMessageEnum {
            /**
             * <code>ACK = 0;</code>
             */
            ACK(0, 0),
            /**
             * <code>HELLO = 1;</code>
             */
            HELLO(1, 1),
            /**
             * <code>WORD = 2;</code>
             */
            WORD(2, 2),
            /**
             * <code>PICTURE = 3;</code>
             */
            PICTURE(3, 3),
            /**
             * <code>VOICE = 4;</code>
             */
            VOICE(4, 4),
            /**
             * <code>VIDEO = 5;</code>
             */
            VIDEO(5, 5),
            /**
             * <code>OTHER = 6;</code>
             */
            OTHER(6, 6),;

            /**
             * <code>ACK = 0;</code>
             */
            public static final int ACK_VALUE = 0;
            /**
             * <code>HELLO = 1;</code>
             */
            public static final int HELLO_VALUE = 1;
            /**
             * <code>WORD = 2;</code>
             */
            public static final int WORD_VALUE = 2;
            /**
             * <code>PICTURE = 3;</code>
             */
            public static final int PICTURE_VALUE = 3;
            /**
             * <code>VOICE = 4;</code>
             */
            public static final int VOICE_VALUE = 4;
            /**
             * <code>VIDEO = 5;</code>
             */
            public static final int VIDEO_VALUE = 5;
            /**
             * <code>OTHER = 6;</code>
             */
            public static final int OTHER_VALUE = 6;
            private static final MessageType[] VALUES = values();
            private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
                    internalValueMap =
                    new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
                        public MessageType findValueByNumber(int number) {
                            return MessageType.valueOf(number);
                        }
                    };
            private final int index;
            private final int value;

            private MessageType(int index, int value) {
                this.index = index;
                this.value = value;
            }

            public static MessageType valueOf(int value) {
                switch (value) {
                    case 0:
                        return ACK;
                    case 1:
                        return HELLO;
                    case 2:
                        return WORD;
                    case 3:
                        return PICTURE;
                    case 4:
                        return VOICE;
                    case 5:
                        return VIDEO;
                    case 6:
                        return OTHER;
                    default:
                        return null;
                }
            }

            public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
            internalGetValueMap() {
                return internalValueMap;
            }

            public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
                return limk.p2pchat.basic.MessageBasic.MessageEntity.getDescriptor().getEnumTypes().get(0);
            }

            public static MessageType valueOf(
                    com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
                if (desc.getType() != getDescriptor()) {
                    throw new java.lang.IllegalArgumentException(
                            "EnumValueDescriptor is not for this type.");
                }
                return VALUES[desc.getIndex()];
            }

            public final int getNumber() {
                return value;
            }

            public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
                return getDescriptor().getValues().get(index);
            }

            public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
                return getDescriptor();
            }

            // @@protoc_insertion_point(enum_scope:basic.MessageEntity.MessageType)
        }

        /**
         * Protobuf enum {@code basic.MessageEntity.MessageView}
         */
        public enum MessageView
                implements com.google.protobuf.ProtocolMessageEnum {
            /**
             * <code>SEND = 0;</code>
             */
            SEND(0, 0),
            /**
             * <code>RECEIVE = 1;</code>
             */
            RECEIVE(1, 1),;

            /**
             * <code>SEND = 0;</code>
             */
            public static final int SEND_VALUE = 0;
            /**
             * <code>RECEIVE = 1;</code>
             */
            public static final int RECEIVE_VALUE = 1;
            private static final MessageView[] VALUES = values();
            private static com.google.protobuf.Internal.EnumLiteMap<MessageView>
                    internalValueMap =
                    new com.google.protobuf.Internal.EnumLiteMap<MessageView>() {
                        public MessageView findValueByNumber(int number) {
                            return MessageView.valueOf(number);
                        }
                    };
            private final int index;
            private final int value;

            private MessageView(int index, int value) {
                this.index = index;
                this.value = value;
            }

            public static MessageView valueOf(int value) {
                switch (value) {
                    case 0:
                        return SEND;
                    case 1:
                        return RECEIVE;
                    default:
                        return null;
                }
            }

            public static com.google.protobuf.Internal.EnumLiteMap<MessageView>
            internalGetValueMap() {
                return internalValueMap;
            }

            public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
                return limk.p2pchat.basic.MessageBasic.MessageEntity.getDescriptor().getEnumTypes().get(1);
            }

            public static MessageView valueOf(
                    com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
                if (desc.getType() != getDescriptor()) {
                    throw new java.lang.IllegalArgumentException(
                            "EnumValueDescriptor is not for this type.");
                }
                return VALUES[desc.getIndex()];
            }

            public final int getNumber() {
                return value;
            }

            public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
                return getDescriptor().getValues().get(index);
            }

            public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
                return getDescriptor();
            }

            // @@protoc_insertion_point(enum_scope:basic.MessageEntity.MessageView)
        }

        /**
         * Protobuf enum {@code basic.MessageEntity.MessageState}
         */
        public enum MessageState
                implements com.google.protobuf.ProtocolMessageEnum {
            /**
             * <code>SENDING = 0;</code>
             */
            SENDING(0, 0),
            /**
             * <code>SEND_FAIL = 1;</code>
             */
            SEND_FAIL(1, 1),
            /**
             * <code>SEND_OK = 2;</code>
             */
            SEND_OK(2, 2),;

            /**
             * <code>SENDING = 0;</code>
             */
            public static final int SENDING_VALUE = 0;
            /**
             * <code>SEND_FAIL = 1;</code>
             */
            public static final int SEND_FAIL_VALUE = 1;
            /**
             * <code>SEND_OK = 2;</code>
             */
            public static final int SEND_OK_VALUE = 2;
            private static final MessageState[] VALUES = values();
            private static com.google.protobuf.Internal.EnumLiteMap<MessageState>
                    internalValueMap =
                    new com.google.protobuf.Internal.EnumLiteMap<MessageState>() {
                        public MessageState findValueByNumber(int number) {
                            return MessageState.valueOf(number);
                        }
                    };
            private final int index;
            private final int value;

            private MessageState(int index, int value) {
                this.index = index;
                this.value = value;
            }

            public static MessageState valueOf(int value) {
                switch (value) {
                    case 0:
                        return SENDING;
                    case 1:
                        return SEND_FAIL;
                    case 2:
                        return SEND_OK;
                    default:
                        return null;
                }
            }

            public static com.google.protobuf.Internal.EnumLiteMap<MessageState>
            internalGetValueMap() {
                return internalValueMap;
            }

            public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
                return limk.p2pchat.basic.MessageBasic.MessageEntity.getDescriptor().getEnumTypes().get(2);
            }

            public static MessageState valueOf(
                    com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
                if (desc.getType() != getDescriptor()) {
                    throw new java.lang.IllegalArgumentException(
                            "EnumValueDescriptor is not for this type.");
                }
                return VALUES[desc.getIndex()];
            }

            public final int getNumber() {
                return value;
            }

            public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
                return getDescriptor().getValues().get(index);
            }

            public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
                return getDescriptor();
            }

            // @@protoc_insertion_point(enum_scope:basic.MessageEntity.MessageState)
        }

        /**
         * Protobuf type {@code basic.MessageEntity}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:basic.MessageEntity)
                limk.p2pchat.basic.MessageBasic.MessageEntityOrBuilder {
            private int bitField0_;
            private long messageID_;
            private long uUID_;
            private java.lang.Object messageDate_ = "";
            private int messageType_;
            private int messageState_;
            private int messageView_;
            private boolean isRead_;
            private java.lang.Object messageHead_ = "";
            private com.google.protobuf.ByteString messagePayload_ = com.google.protobuf.ByteString.EMPTY;

            // Construct using limk.p2pchat.basic.MessageBasic.MessageEntity.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return limk.p2pchat.basic.MessageBasic.internal_static_basic_MessageEntity_descriptor;
            }

            private static Builder create() {
                return new Builder();
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return limk.p2pchat.basic.MessageBasic.internal_static_basic_MessageEntity_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                limk.p2pchat.basic.MessageBasic.MessageEntity.class, limk.p2pchat.basic.MessageBasic.MessageEntity.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                messageID_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000001);
                uUID_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000002);
                messageDate_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                messageType_ = 0;
                bitField0_ = (bitField0_ & ~0x00000008);
                messageState_ = 0;
                bitField0_ = (bitField0_ & ~0x00000010);
                messageView_ = 0;
                bitField0_ = (bitField0_ & ~0x00000020);
                isRead_ = false;
                bitField0_ = (bitField0_ & ~0x00000040);
                messageHead_ = "";
                bitField0_ = (bitField0_ & ~0x00000080);
                messagePayload_ = com.google.protobuf.ByteString.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000100);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return limk.p2pchat.basic.MessageBasic.internal_static_basic_MessageEntity_descriptor;
            }

            public limk.p2pchat.basic.MessageBasic.MessageEntity getDefaultInstanceForType() {
                return limk.p2pchat.basic.MessageBasic.MessageEntity.getDefaultInstance();
            }

            public limk.p2pchat.basic.MessageBasic.MessageEntity build() {
                limk.p2pchat.basic.MessageBasic.MessageEntity result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public limk.p2pchat.basic.MessageBasic.MessageEntity buildPartial() {
                limk.p2pchat.basic.MessageBasic.MessageEntity result = new limk.p2pchat.basic.MessageBasic.MessageEntity(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.messageID_ = messageID_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.uUID_ = uUID_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.messageDate_ = messageDate_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.messageType_ = messageType_;
                if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
                    to_bitField0_ |= 0x00000010;
                }
                result.messageState_ = messageState_;
                if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
                    to_bitField0_ |= 0x00000020;
                }
                result.messageView_ = messageView_;
                if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
                    to_bitField0_ |= 0x00000040;
                }
                result.isRead_ = isRead_;
                if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
                    to_bitField0_ |= 0x00000080;
                }
                result.messageHead_ = messageHead_;
                if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
                    to_bitField0_ |= 0x00000100;
                }
                result.messagePayload_ = messagePayload_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof limk.p2pchat.basic.MessageBasic.MessageEntity) {
                    return mergeFrom((limk.p2pchat.basic.MessageBasic.MessageEntity) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(limk.p2pchat.basic.MessageBasic.MessageEntity other) {
                if (other == limk.p2pchat.basic.MessageBasic.MessageEntity.getDefaultInstance())
                    return this;
                if (other.hasMessageID()) {
                    setMessageID(other.getMessageID());
                }
                if (other.hasUUID()) {
                    setUUID(other.getUUID());
                }
                if (other.hasMessageDate()) {
                    bitField0_ |= 0x00000004;
                    messageDate_ = other.messageDate_;
                    onChanged();
                }
                if (other.hasMessageType()) {
                    setMessageType(other.getMessageType());
                }
                if (other.hasMessageState()) {
                    setMessageState(other.getMessageState());
                }
                if (other.hasMessageView()) {
                    setMessageView(other.getMessageView());
                }
                if (other.hasIsRead()) {
                    setIsRead(other.getIsRead());
                }
                if (other.hasMessageHead()) {
                    bitField0_ |= 0x00000080;
                    messageHead_ = other.messageHead_;
                    onChanged();
                }
                if (other.hasMessagePayload()) {
                    setMessagePayload(other.getMessagePayload());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasMessageID()) {

                    return false;
                }
                if (!hasUUID()) {

                    return false;
                }
                if (!hasMessageDate()) {

                    return false;
                }
                if (!hasMessageType()) {

                    return false;
                }
                if (!hasMessageState()) {

                    return false;
                }
                if (!hasMessageView()) {

                    return false;
                }
                if (!hasIsRead()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                limk.p2pchat.basic.MessageBasic.MessageEntity parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (limk.p2pchat.basic.MessageBasic.MessageEntity) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>required int64 messageID = 1;</code>
             */
            public boolean hasMessageID() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required int64 messageID = 1;</code>
             */
            public long getMessageID() {
                return messageID_;
            }

            /**
             * <code>required int64 messageID = 1;</code>
             */
            public Builder setMessageID(long value) {
                bitField0_ |= 0x00000001;
                messageID_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int64 messageID = 1;</code>
             */
            public Builder clearMessageID() {
                bitField0_ = (bitField0_ & ~0x00000001);
                messageID_ = 0L;
                onChanged();
                return this;
            }

            /**
             * <code>required int64 UUID = 2;</code>
             */
            public boolean hasUUID() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>required int64 UUID = 2;</code>
             */
            public long getUUID() {
                return uUID_;
            }

            /**
             * <code>required int64 UUID = 2;</code>
             */
            public Builder setUUID(long value) {
                bitField0_ |= 0x00000002;
                uUID_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int64 UUID = 2;</code>
             */
            public Builder clearUUID() {
                bitField0_ = (bitField0_ & ~0x00000002);
                uUID_ = 0L;
                onChanged();
                return this;
            }

            /**
             * <code>required string messageDate = 3;</code>
             */
            public boolean hasMessageDate() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>required string messageDate = 3;</code>
             */
            public java.lang.String getMessageDate() {
                java.lang.Object ref = messageDate_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        messageDate_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>required string messageDate = 3;</code>
             */
            public Builder setMessageDate(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                messageDate_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string messageDate = 3;</code>
             */
            public com.google.protobuf.ByteString
            getMessageDateBytes() {
                java.lang.Object ref = messageDate_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    messageDate_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string messageDate = 3;</code>
             */
            public Builder setMessageDateBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                messageDate_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string messageDate = 3;</code>
             */
            public Builder clearMessageDate() {
                bitField0_ = (bitField0_ & ~0x00000004);
                messageDate_ = getDefaultInstance().getMessageDate();
                onChanged();
                return this;
            }

            /**
             * <code>required int32 messageType = 4;</code>
             */
            public boolean hasMessageType() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }

            /**
             * <code>required int32 messageType = 4;</code>
             */
            public int getMessageType() {
                return messageType_;
            }

            /**
             * <code>required int32 messageType = 4;</code>
             */
            public Builder setMessageType(int value) {
                bitField0_ |= 0x00000008;
                messageType_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int32 messageType = 4;</code>
             */
            public Builder clearMessageType() {
                bitField0_ = (bitField0_ & ~0x00000008);
                messageType_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>required int32 messageState = 5;</code>
             */
            public boolean hasMessageState() {
                return ((bitField0_ & 0x00000010) == 0x00000010);
            }

            /**
             * <code>required int32 messageState = 5;</code>
             */
            public int getMessageState() {
                return messageState_;
            }

            /**
             * <code>required int32 messageState = 5;</code>
             */
            public Builder setMessageState(int value) {
                bitField0_ |= 0x00000010;
                messageState_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int32 messageState = 5;</code>
             */
            public Builder clearMessageState() {
                bitField0_ = (bitField0_ & ~0x00000010);
                messageState_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>required int32 messageView = 6;</code>
             */
            public boolean hasMessageView() {
                return ((bitField0_ & 0x00000020) == 0x00000020);
            }

            /**
             * <code>required int32 messageView = 6;</code>
             */
            public int getMessageView() {
                return messageView_;
            }

            /**
             * <code>required int32 messageView = 6;</code>
             */
            public Builder setMessageView(int value) {
                bitField0_ |= 0x00000020;
                messageView_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int32 messageView = 6;</code>
             */
            public Builder clearMessageView() {
                bitField0_ = (bitField0_ & ~0x00000020);
                messageView_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>required bool isRead = 7;</code>
             */
            public boolean hasIsRead() {
                return ((bitField0_ & 0x00000040) == 0x00000040);
            }

            /**
             * <code>required bool isRead = 7;</code>
             */
            public boolean getIsRead() {
                return isRead_;
            }

            /**
             * <code>required bool isRead = 7;</code>
             */
            public Builder setIsRead(boolean value) {
                bitField0_ |= 0x00000040;
                isRead_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required bool isRead = 7;</code>
             */
            public Builder clearIsRead() {
                bitField0_ = (bitField0_ & ~0x00000040);
                isRead_ = false;
                onChanged();
                return this;
            }

            /**
             * <code>optional string messageHead = 8;</code>
             */
            public boolean hasMessageHead() {
                return ((bitField0_ & 0x00000080) == 0x00000080);
            }

            /**
             * <code>optional string messageHead = 8;</code>
             */
            public java.lang.String getMessageHead() {
                java.lang.Object ref = messageHead_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        messageHead_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string messageHead = 8;</code>
             */
            public Builder setMessageHead(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000080;
                messageHead_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string messageHead = 8;</code>
             */
            public com.google.protobuf.ByteString
            getMessageHeadBytes() {
                java.lang.Object ref = messageHead_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    messageHead_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string messageHead = 8;</code>
             */
            public Builder setMessageHeadBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000080;
                messageHead_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string messageHead = 8;</code>
             */
            public Builder clearMessageHead() {
                bitField0_ = (bitField0_ & ~0x00000080);
                messageHead_ = getDefaultInstance().getMessageHead();
                onChanged();
                return this;
            }

            /**
             * <code>optional bytes messagePayload = 9;</code>
             */
            public boolean hasMessagePayload() {
                return ((bitField0_ & 0x00000100) == 0x00000100);
            }

            /**
             * <code>optional bytes messagePayload = 9;</code>
             */
            public com.google.protobuf.ByteString getMessagePayload() {
                return messagePayload_;
            }

            /**
             * <code>optional bytes messagePayload = 9;</code>
             */
            public Builder setMessagePayload(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000100;
                messagePayload_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional bytes messagePayload = 9;</code>
             */
            public Builder clearMessagePayload() {
                bitField0_ = (bitField0_ & ~0x00000100);
                messagePayload_ = getDefaultInstance().getMessagePayload();
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:basic.MessageEntity)
        }

        // @@protoc_insertion_point(class_scope:basic.MessageEntity)
    }

    /**
     * Protobuf type {@code basic.UserEntity}
     */
    public static final class UserEntity extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:basic.UserEntity)
            UserEntityOrBuilder {
        public static final int UUID_FIELD_NUMBER = 1;
        public static final int NAME_FIELD_NUMBER = 2;
        private static final UserEntity defaultInstance;
        private static final long serialVersionUID = 0L;
        public static com.google.protobuf.Parser<UserEntity> PARSER =
                new com.google.protobuf.AbstractParser<UserEntity>() {
                    public UserEntity parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new UserEntity(input, extensionRegistry);
                    }
                };

        static {
            defaultInstance = new UserEntity(true);
            defaultInstance.initFields();
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;
        private int bitField0_;
        private long uuid_;
        private java.lang.Object name_;
        private byte memoizedIsInitialized = -1;
        private int memoizedSerializedSize = -1;

        // Use UserEntity.newBuilder() to construct.
        private UserEntity(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }
        private UserEntity(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }
        private UserEntity(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            uuid_ = input.readInt64();
                            break;
                        }
                        case 18: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000002;
                            name_ = bs;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static UserEntity getDefaultInstance() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return limk.p2pchat.basic.MessageBasic.internal_static_basic_UserEntity_descriptor;
        }

        public static limk.p2pchat.basic.MessageBasic.UserEntity parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static limk.p2pchat.basic.MessageBasic.UserEntity parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static limk.p2pchat.basic.MessageBasic.UserEntity parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static limk.p2pchat.basic.MessageBasic.UserEntity parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static limk.p2pchat.basic.MessageBasic.UserEntity parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static limk.p2pchat.basic.MessageBasic.UserEntity parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static limk.p2pchat.basic.MessageBasic.UserEntity parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static limk.p2pchat.basic.MessageBasic.UserEntity parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static limk.p2pchat.basic.MessageBasic.UserEntity parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static limk.p2pchat.basic.MessageBasic.UserEntity parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public static Builder newBuilder(limk.p2pchat.basic.MessageBasic.UserEntity prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public UserEntity getDefaultInstanceForType() {
            return defaultInstance;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return limk.p2pchat.basic.MessageBasic.internal_static_basic_UserEntity_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            limk.p2pchat.basic.MessageBasic.UserEntity.class, limk.p2pchat.basic.MessageBasic.UserEntity.Builder.class);
        }

        @java.lang.Override
        public com.google.protobuf.Parser<UserEntity> getParserForType() {
            return PARSER;
        }

        /**
         * <code>required int64 uuid = 1;</code>
         */
        public boolean hasUuid() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required int64 uuid = 1;</code>
         */
        public long getUuid() {
            return uuid_;
        }

        /**
         * <code>required string name = 2;</code>
         */
        public boolean hasName() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>required string name = 2;</code>
         */
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    name_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string name = 2;</code>
         */
        public com.google.protobuf.ByteString
        getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            uuid_ = 0L;
            name_ = "";
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasUuid()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasName()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt64(1, uuid_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getNameBytes());
            }
            getUnknownFields().writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(1, uuid_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, getNameBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code basic.UserEntity}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:basic.UserEntity)
                limk.p2pchat.basic.MessageBasic.UserEntityOrBuilder {
            private int bitField0_;
            private long uuid_;
            private java.lang.Object name_ = "";

            // Construct using limk.p2pchat.basic.MessageBasic.UserEntity.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return limk.p2pchat.basic.MessageBasic.internal_static_basic_UserEntity_descriptor;
            }

            private static Builder create() {
                return new Builder();
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return limk.p2pchat.basic.MessageBasic.internal_static_basic_UserEntity_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                limk.p2pchat.basic.MessageBasic.UserEntity.class, limk.p2pchat.basic.MessageBasic.UserEntity.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                uuid_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000001);
                name_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return limk.p2pchat.basic.MessageBasic.internal_static_basic_UserEntity_descriptor;
            }

            public limk.p2pchat.basic.MessageBasic.UserEntity getDefaultInstanceForType() {
                return limk.p2pchat.basic.MessageBasic.UserEntity.getDefaultInstance();
            }

            public limk.p2pchat.basic.MessageBasic.UserEntity build() {
                limk.p2pchat.basic.MessageBasic.UserEntity result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public limk.p2pchat.basic.MessageBasic.UserEntity buildPartial() {
                limk.p2pchat.basic.MessageBasic.UserEntity result = new limk.p2pchat.basic.MessageBasic.UserEntity(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.uuid_ = uuid_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.name_ = name_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof limk.p2pchat.basic.MessageBasic.UserEntity) {
                    return mergeFrom((limk.p2pchat.basic.MessageBasic.UserEntity) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(limk.p2pchat.basic.MessageBasic.UserEntity other) {
                if (other == limk.p2pchat.basic.MessageBasic.UserEntity.getDefaultInstance())
                    return this;
                if (other.hasUuid()) {
                    setUuid(other.getUuid());
                }
                if (other.hasName()) {
                    bitField0_ |= 0x00000002;
                    name_ = other.name_;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasUuid()) {

                    return false;
                }
                if (!hasName()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                limk.p2pchat.basic.MessageBasic.UserEntity parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (limk.p2pchat.basic.MessageBasic.UserEntity) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>required int64 uuid = 1;</code>
             */
            public boolean hasUuid() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required int64 uuid = 1;</code>
             */
            public long getUuid() {
                return uuid_;
            }

            /**
             * <code>required int64 uuid = 1;</code>
             */
            public Builder setUuid(long value) {
                bitField0_ |= 0x00000001;
                uuid_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int64 uuid = 1;</code>
             */
            public Builder clearUuid() {
                bitField0_ = (bitField0_ & ~0x00000001);
                uuid_ = 0L;
                onChanged();
                return this;
            }

            /**
             * <code>required string name = 2;</code>
             */
            public boolean hasName() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>required string name = 2;</code>
             */
            public java.lang.String getName() {
                java.lang.Object ref = name_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        name_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>required string name = 2;</code>
             */
            public Builder setName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string name = 2;</code>
             */
            public com.google.protobuf.ByteString
            getNameBytes() {
                java.lang.Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string name = 2;</code>
             */
            public Builder setNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string name = 2;</code>
             */
            public Builder clearName() {
                bitField0_ = (bitField0_ & ~0x00000002);
                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:basic.UserEntity)
        }

        // @@protoc_insertion_point(class_scope:basic.UserEntity)
    }

    // @@protoc_insertion_point(outer_class_scope)
}
